language: node_js
node_js:
  - 13
  - 12
  - 10

services:
  - docker

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose stop
  - docker-compose rm
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker-compose create
  - docker-compose up -d
  - npm config set @sap:registry https://npm.sap.com
  - npm i @sap/hana-client hdb-pool
  - cp ormconfig.travis.json ormconfig.json

script:
  - npm run lint
  - npx nyc npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
