sudo: required
language: node_js
node_js:
  - 11
  - 10
  - 9
  - 8

cache: npm

services:
  - docker

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d
  - cp ormconfig.travis.json ormconfig.json
  - npm install sqlite3 --build-from-source

script:
  - npm run lint
  - npm t

after_success:
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)
