version: "3"
services:

  # sap hana (works only on linux)
  hanaexpress:
    image: "store/saplabs/hanaexpress:2.00.040.00.20190729.1"
    container_name: "typeorm-hanaexpress"
    hostname: hxe
    command:
     [
       "--passwords-url",
       "file:////hana/hxe-config.json",
       "--agree-to-sap-license",
     ]
    ulimits:
     nofile: 1048576
    sysctls:
     - kernel.shmmax=1073741824
     - net.ipv4.ip_local_port_range=40000 60999
     - kernel.shmmni=524288
     - kernel.shmall=8388608
    volumes:
     - volume-hana-xe:/hana/mounts
     - ./docker/hana/hxe-config.json:/hana/hxe-config.json
    ports:
     - 39013:39013
     - 39017:39017
     - 39041-39045:39041-39045
     - 1128-1129:1128-1129
     - 59013-59014:59013-59014

volumes:
  volume-hana-xe:
